name: Run all project tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: 0 19 * * 2

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
